import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/custom/NavbarWrapper";
import Footer from "@/components/custom/Footer";
import { Toaster } from "@/components/ui/sonner";
import AuthContextProvider from "@/store/AuthContext";

export const metadata: Metadata = {
  title: "Chrono | Job Application Tracking",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="bg-custom-background">
        <AuthContextProvider>
          <NavbarWrapper />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
