import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/custom/Navbar'
import Footer from '@/components/custom/Footer'
import { Toaster } from '@/components/ui/sonner'
import AuthContextProvider from '@/store/AuthContext'

export const metadata: Metadata = {
  title: 'Chrono',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthContextProvider>
          <Navbar />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  )
}
